sudo: required

services:
  - docker

language: c

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

script:
  # Install required ansible roles
  - docker build -t suizman/dmux .

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2ab592bc2cf1cb29a33a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
